# Generated by Django 4.0.2 on 2022-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='status',
            field=models.TextField(default='PENDING'),
        ),
    ]
