# Generated by Django 4.0.2 on 2022-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_status_takeappointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeappointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.TextField(default='PENDING'),
        ),
    ]
