# Generated by Django 4.0.2 on 2022-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_takeappointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeappointment',
            name='message',
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='takeappointment',
            name='the_challenge',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
