# Generated by Django 4.0.2 on 2022-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
